### PR TITLE
the info map is now being marshaled to json in its own sub node to av…

### PR DESCRIPTION
**Pull request by bestform**
…oid overwriting the status

### CODE REVIEW

**Comment by bestform** [comment]
The issue discussing this PR can be found at https://github.com/dimiro1/health/issues/9

**Comment by bestform** [comment]
oh.. checks failed.. i will check the db and url tests.

**Comment by dimiro1** [comment]
Hey @bestform sorry about it, I was thinking about this problem and I decided to give priority to the status defined in the Health struct. If some check add a status key, it will not be rendered in the json. Take a look at the master branch.

https://github.com/dimiro1/health/commit/68671c53fef441bd953e542ca449df7863ed111d

**Comment by bestform** [comment]
ok. fair enough, that is what open source is all about :)

**Comment by dimiro1** [comment]
@bestform Thank you so much for giving so much attention to this project. Lets keep working.

**Comment by bestform** [comment]
no problem :) i love contributing to open source projects in my free time. making better software via open source is what i truly endorse. Keep up the good work :)

**Pull request closed without merging**
