### PR TITLE
health status now has its own type and it isn't being exported

### PR DESCRIPTION
**Pull request by bestform**
Here we go. The corresponding issue discussing this topic can be found at https://github.com/dimiro1/health/issues/6

### CODE REVIEW

**Comment by dimiro1** [comment]
We decided to not export the status member on the Health struct, thats ok. I do not see a reason to make the status its own type. We could keep it as string and avoid this String() method. To finish I prefer not export the status constants, because it makes no sense outside the health package. What do you think?

```go
const (
	up           = "UP"
	down         = "DOWN"
	outOfService = "OUT_OF_SERVICE"
	unknown      = "UNKNOWN"
)

type Health struct {
	status string
	Info   map[string]interface{}
}

func (h Health) MarshalJSON() ([]byte, error) {
	data := map[string]interface{}{}
	data["status"] = h.status

	for k, v := range h.Info {
		data[k] = v
	}

	return json.Marshal(data)
}

func (h Health) IsUnknown() bool {
	return h.status == unknown
}
```

**Comment by bestform** [comment]
fair enough. The String() method is a caveat. BUT: we still can make it its own type and lose the String method, when we just make the custom type a string instead of an int. let me update this pr to show you, how I would implement it. Just a sec.

**Comment by bestform** [comment]
OK, here we go. This is how I would build it with string instead of int.

Just a note: as you do not export the status anymore, the tests checking the actual status are kind of shady, as they now check an implementation detail instead of the public API.

**Comment by bestform** [comment]
One additional note, just to stress why I think it is good to have a type for the status: this way, it is impossible to accidentally assign a value that cannot be interpreted. So no "UNKOWN" or "DWON" status possible ;) (yeah.. been there)

**Comment by dimiro1** [comment]
Thank you @bestform. It looks very good to me.

**Pull request merged**
